const products = {
    "Foxtail Millet":3,
    "Little Millet":3,
    "Proso Millet":3,
    "Kodo Millet":3,
    "Ragi Whole":2,
    "Jawar Whole":2.5,
    "Browntop Millet":3.85,
    "Semolina":3.15,
    "Wheat Flour":4,
    "Ragi Flour":2,
    "Bajara Flour":2,
    "Bajara Whole":3,
    "Jawar Flour":3,
    "Multi Millet Flour":2.15,
    "Barnyard Millet":2.14,
    "Barnyard Millet Flour":2.45,
    "Foxtail Millet Flour":2,
    "Little Millet Flour":3,
    "Proso Millet Flour":3,
    "Kodo Millet Flour":3,
};